# Generated by Django 3.0.8 on 2020-08-07 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_confirmed_email',
            field=models.BooleanField(default=False, verbose_name='is confirmed email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='slug'),
        ),
    ]
