# Generated by Django 3.0.8 on 2020-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200808_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_sent_email',
            field=models.BooleanField(default=False, verbose_name='sent email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_confirmed_email',
            field=models.BooleanField(default=False, verbose_name='confirmed email'),
        ),
    ]
