# Generated by Django 3.0.8 on 2020-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200808_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_tiny', verbose_name='avatar thumbnail small'),
        ),
        migrations.AddField(
            model_name='account',
            name='thumbnail_tiny',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_tiny', verbose_name='avatar thumbnail tiny'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='avatar'),
        ),
    ]
